### ISSUE TITLE
It's SessionManager>>logError: thread safe?

### ISSUE THREAD

**Issue by fxgallego** [dolphinsmalltalk/DolphinVM#124]
I've followed the VMLibrary dump implementation that ends in the VM's [Dump2 method](https://github.com/dolphinsmalltalk/DolphinVM/blob/877850b4d9ba0e141f4ee2c83738683f2d6b5c6f/CrashDump.cpp#L251)

We have a swazoo server that logs internal server errors using #logError: and when it's stressed with a large number of requests handled by forked processes causes Dolphin to crash "apparently" when #logError: is called.

When we don't log errors, we don't have any problems so I suspect that this is related to concurrency issues.

**Comment by blairmcg** [comment]
`SessionManager>>logError:`, yes, should be, although only assuming the Exception being logged implements `description` in a thread safe way, which normally should be the case. There is otherwise no shared state in the image that gets updated. `DevelopmentSessionManager>>logError:`, no, that won't be safe unless running in unattended mode.
If it's crashing in the VM Dump call, it's more likely due to a bug in that. It does some decoding of stuff on the stack, so depending on what is on the stack at the time different C++ code is going to run. To diagnose any issue there you'll probably have to try capturing a Windows dump, then open the dump in VS or (if you are feeling brave) windbg.
Another possibility is that the Exception>>description method is faulting on some specific exceptions. If that happens you might get a recursive logging and a fatal stack fault.

**Comment by fxgallego** [comment]
Thanks Blair. I'll check again taking into account this possibilities.
I suspect that Dump2 is the culprit but not found yet a way to reproduce this isolated from the entire app.

As for capture a windows dump, should I [use this](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181(v=vs.85).aspx) ?

**Comment by blairmcg** [comment]
Yes, that seems like a good way.

**Comment by fxgallego** [comment]
I think this could be closed. Maybe the error was caused by our own internal code.
