### ISSUE TITLE
Migrate to Visual Studio 2017 / toolset v141

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/DolphinVM#130]
It's desirable to support the current version of Visual Studio.
Tying the build with VStudio 2017 currently yields errors.
(which are above my understanding in complexity to fix :)

**Comment by blairmcg** [comment]
Yes I have noticed some errors with the v141 C++ toolset, but I think they are due to the errors in the targets files in that version. I believe if you decline the upgrade prompt and stay on the v140 toolset that you will be able to work with VS2017.
I am going to report the bug in the targets to Microsoft at some point, but I wanted to try and find a workaround too.

**Comment by FunctionPoint** [comment]
Thanks for the tip. Installing the v140 toolset in VStudio 2017 does indeed make it work.

**Comment by jgfoster** [comment]
With 24f76099bf865206ed72b97bbae901a9cc7e59d6 I'm using VS2017 and toolset v141 (by default; I intended to stay with v140 because this issue remains open) without any problems.
