### ISSUE TITLE
7.0.44 hangs on startup

### ISSUE THREAD

**Issue by andygraham** [dolphinsmalltalk/DolphinVM#137]
Windows 10 Pro on a Surface Studio.

I was previously running VM 7.0.42 which I copied to my Program Files (x86)\Dolphin Smalltalk 7 folder which was installed from the 7.0.32 core image Dolphin7Setup.exe.

I copied the 7.0.44 VM files to that folder but when I start Dolphin I get a busy cursor but the System Shell does not appear.  Dolphin Smalltalk  Launcher (32 bit) appears in the Task Manager but nothing further happens. I have to either kill that task or wait for it to disappear after a short while.

Copying the 7.0.42 files back to the Dolphin program folder restores normal operation.

**Comment by blairmcg** [comment]
@andygraham, you'll need to use the latest image sources if you want this to work since the VM is no longer exporting certain functions required by an older image, and so it requires the corresponding changes to the image. You'll need to clone the dolphinsmalltalk/Dolphin repo and boot it, following the instructions in the readme. You may want to create a clone of the repo to preserve your own changes and make any contributions you'd like to submit via pull requests.

**Comment by andygraham** [comment]
That explains it. Thanks for the info Blair. All this GitHub stuff is a bit beyond this old man so I  think I'll stick with 7.0.42 till there is a new Dolphin7setup.exe release some time in the future.
