### ISSUE TITLE
VMTest>>#testOverlappedCallTermination

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#14]
In the Debug configuration this test triggers a break in `thrdcall.cpp`:
355: `HARDASSERT(::GetCurrentThreadId() == Interpreter::MainThreadId());`
And in `process.cpp`:
1000: `HARDASSERT(newActivePriority >= highestPriorityWaiting);`

Again, given the name of the test (`#testOverlappedCallTermination`) it seems plausible that there is some confusion about the current active thread and its priority.

**Comment by blairmcg** [comment]
I think the thrdcall.cpp assertion is wrong. The destructor is called when the last ref to the C++ OverlappedCall object is released, which could happen on a background thread when the Smalltalk process is terminated.
Not sure about the 2nd. That could well be the overlapped call stuff hard reactivating a process out of priority order. Fixing it is likely to be tricky however.
To be honest I don't ever remember running the Smalltalk tests on a debug VM, it was just too slow. The debug VM was only used in extremis to investigate VM bugs, and mostly startup bugs that required tracing bytecode execution. Because of the extreme overhead of running the debug VM, most of the time I debugged using a release build, but turned off the compiler optimization. In fact there used to be a build configuration for this.

**Comment by blairmcg** [comment]
No longer repro's
