### ISSUE TITLE
Tag 5.0.51 seems wrong after tag 7.0.51

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#147]
It seems that the latest tag should be v7.0.52.

![screen shot 2017-11-28 at 9 12 52 am](https://user-images.githubusercontent.com/1577872/33333942-3001931a-d41d-11e7-846c-7d8acda7348e.png)

**Comment by blairmcg** [comment]
The latest tag is v7.0.51. If I clone a new copy of the repo, that is what I see for `git describe` so that is what should be getting built into the VM. v5.0.51 is there in the full list - it was an interim mistake that I have tried to delete, but points at the same commit so obviously causes issues in some circumstance. I'll try and delete it again.

**Comment by blairmcg** [comment]
Ah, deleting locally and pushing tags doesn't do anything. I've deleted it directly on GitHub, so is gone now. Sorry for the trouble.
