### ISSUE TITLE
Upgrade to current Windows 10 SDK: v16299

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/DolphinVM#150]
The current VM is targeted towards: v15063.

**Comment by blairmcg** [comment]
If there is a compelling reason to do this (e.g. desire to use a new API), but otherwise I don't think we should unless v16299 is the default for new installations of VS2017. Otherwise it forces everyone to have to go and install the new SDK without any particular upside.
Its reasonable to keep this issue around, however, until the reason or reasons arise.

**Comment by blairmcg** [comment]
The 7.1 branch is now targeting v17134.0. I don't think it is worth changing the 7.0 build.
