### ISSUE TITLE
Text entry field problems

### ISSUE THREAD

**Issue by jgfoster** [dolphinsmalltalk/DolphinVM#158]
Up through 294fbd6fa35169b1234ebe7322d072bcad9b0167 my text entry fields were properly filled (as shown below): 

![screen shot 2018-02-19 at 9 36 27 am](https://user-images.githubusercontent.com/1577872/36391207-654f6a64-155a-11e8-9997-fdcface8ee26.png) 

With b4c5b80bc02a7731df97e8a625d6b31e803d9c95 there is a change in behavior. I am only getting one character from each field (as shown below):

![screen shot 2018-02-19 at 9 49 04 am](https://user-images.githubusercontent.com/1577872/36391209-67975d04-155a-11e8-8447-7084868478af.png)

As far as I can tell, the data I'm putting into the fields has not changed.

**Comment by blairmcg** [comment]
The change you reference is a change in behaviour in that formerly when the value of a BSTR was queried from a VARIANT, the primitive would return an Ansi string. The result will now be a Utf16String. I realise this may be a breaking change, but the previous behaviour was wrong (may cause data loss) and has to be fixed to move forward and properly support international language characters. In an intermediate commit I did return UTF8 instead, and certainly when sticking to the English alphabet this would be completely compatible. I decided however, that since the UTF8 support is nascent, that this would present a false sense of correctness and produce subtle/non-obvious errors that would only show up with certain data. It seemed better to return a string in that native encoding that COM uses, and make it obvious that an explicit #asUtf8String or #asAnsiString may be needed.
The behaviour you are seeing is exactly what you'd get if passing Utf16Strings to something expecting to receive byte strings - for ascii characters the UTF16LE encoding is the ascii code point followed by a zero byte, so if a Utf16String is treated as a byte string it will appear to C code to have one character and a null terminator. The VM has been changed to apply a conversion automatically for lpstr arguments to external calls, but there are many other potential places an explicit conversion may be needed.
If your code doesn't involve COM and BSTRs it would be useful to understand what is going on so we can fix it. To debug I suggest stepping through and looking at the types of the strings you have, where they came from, and what they are being passed to.
I'm sorry for the inconvenience, but the international character omelette is going to require breaking some œuf.

**Comment by jgfoster** [comment]
Thanks for the explanation and rationale. I'm certainly fine with moving forward toward international support. A simplified version of my code includes the following:

```
onViewOpened

	| xml element attribute |
	super onViewOpened.
	xml := '<foo attr="bar"></foo>'.
	element := (IXMLDOMDocument new loadText: xml) documentElement.
	attribute := element getAttribute: 'attr'.
	textPresenter value: attribute.
```

So it seems that the XML attribute is coming back as UTF16. If I send #'asAnsiString' to attribute then the text shows properly, so that is a fine work-around for me.

Should the UI elements accept UTF16? If so, then should the original code work? If not, then should the called methods automatically convert to ANSI? My vague recollection is that many Win32 functions have -A and -W variants. Is your work related to this? Should Dolphin have both? Would it make sense to have a global setting to designate which variant to use?

P.S. Are there any simple (but helpful) grunt tasks related to internationalization?

**Comment by blairmcg** [comment]
Yes James, the intention is that eventually the UI elements will accept and handle UTF16 (or UTF8) correctly because they'll be operating in UTF16 mode (which Microsoft historically referred to as "Unicode").  A bit like this:

![image](https://user-images.githubusercontent.com/15128107/36439203-0f31b4d8-1664-11e8-801f-7864a1e7e05b.png)

(Ok, frivolous example, and there won't be a separate TextEditW).

The immediate intention is that they controls should accept any text encoding, and convert as necessary. Since the underlying controls are opened in Ansi mode today , they'll lose multi-byte characters. Although the VM changes would enable this, it doesn't work because of another "bug" in the declaration of the `UserLibrary>>setWindowText:lpString:` method, i.e.:
```
setWindowText: aWindowHandle lpString: aString
...
	<stdcall: bool SetWindowTextA handle lpvoid>
	^self invalidCall
```
The string parameter is declared as `lpvoid`, which means the VM won't know to convert it ("bug" is in in quotes as this may have been a deliberate choice to allow integer pointer values to be passed, or it might just be because it was done so early on that the FFI didn't yet support string arguments). If you try switching that to `lpstr`, you might find you don't need the `#asAnsiString`, which would be preferable as the latter conversion will make your code explicitly discard many non ANSI characters even when the UI does eventually support them. BTW: It is also possible to modify this method to use `SetWindowTextW` and set the parameter type to `lpwstr`.  This will work because Windows knows that the target is not a Unicode window, and so it will perform a conversion before forwarding the text itself. I will be changing the method this way, as then it will also continue to work when the control is created as a Unicode window.

I hope that answers most of your questions. My general principle will be to move the Dolphin Views over to using Unicode windows, rather than there being a switch, or parallel classes. The intention is to as far as possible replace the use of the Win32 -A API variants you mention with the -W versions. This may be harder that having both and switching between them, but ultimately the result will be cleaner and simpler. It should also be more performant since the underlying Windows implementations are using UTF16 natively, and supporting Ansi/byte encoding as a compability mode. This means that when you enquire the text from a control, you'll get back a `Utf16String`. Or in the case of the Scintilla control, you'll get a `Utf8String`. It's then a case of making more other code aware of String encodings (e.g. Streams) and making them convert implicitly according to the encoding they are expecting. What we don't want is explicit conversions sprinkled all over the place, all though we might need some to begin with. It might make sense for Views to have a configurable encoding too, but the underlying Windows controls can just be used in Unicode mode all the time.
Unfortunately this is going to take a lot of sorting out, and there might be some grunt work to do, but none that is immediately obvious - in fact it's going to be tricky to do if it is to be done elegantly based on my experiments so far. I had a go at just flipping the code editor views to utf8 and although it "just worked", it also made me realise the implications in that any previous code text using the 128..255 Ansi code page characters, including standard accented characters, would get corrupted. I've now started on an approach of flipping all the Views to Unicode, but maintaining the Ansi string "interface", as this allows for an incremental approach.
