### ISSUE TITLE
Request to borrow Dolpins icons art 

### ISSUE THREAD

**Issue by haijin-development** [dolphinsmalltalk/DolphinVM#182]
Hi @blairmc-msft, Andy,

This may be an unusual request but could I borrow Dolphin's tiny icons for a Dolphin very much like browser for Ruby?

The Ruby browser is this: [https://github.com/haijin-development/ruby-sirens](https://github.com/haijin-development/ruby-sirens) and the main reason I've implemented it is because I wanted a Dolphin like browser for Ruby.

Dolphin is by far the most elegant and beautiful programming environment I've ever worked with and I would love to have its same icons in the browser.

Of course I will mention the source of the icons, including the fact that is one of the finest development environments out there.

Thanks in advance.

**Comment by fxgallego** [comment]
@haijin-development cool stuff that Ruby browser. I remember looking for something like that in my beginnings with Ruby. Now I'm using RubyMine and suffering it's limitations but also loving all the tools it offers.

**Comment by blairmcg** [comment]
A number of the icons are Windows icons or derived from them by adding overlays, etc. If your tool runs on Windows, then the users would have a Windows license, so they are entitled to use those icons, but otherwise I guess not. I don't have a problem with you using the ones I have created, but there are not many of those, and I can't remember which they are. Sorry the answer is not more definitive.

**Comment by haijin-development** [comment]
@blairmcg Oh, a pitty. The GUI is running on linux gnome right now, so I guess I'll just miss Dolphins icons.
@fxgallego Thanks! Sirens is not RubyMine thou, just a couple of utilities for browsing objects and code in the Smalltalk way during development but specifically adapted to Ruby code (which makes a heavy use of mixins, for instance).

Thanks both of you for you answers.
