### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by FunctionPoint** [dolphinsmalltalk/DolphinVM#7]
The VM currently compiles in only Visual Studio 2013, using release build.
For better community support it would be good to port the VM to the current Visual Studio 2015.
The VM project is quite low-level complex, so a "technical" port with minimal changes would be a good start. Reactoring to be done later.
Support for olders versions of Windows and Dolphin could be removed for simplicity.
.
I've looked into this, but to be honest, it is too complex for me in the time I have available:
Too many macro's and old Windows API stuff.

**Comment by DmitrySJohan** [comment]
Frankly speaking VM can be buld for VisualStudio 2015 but will not run because CRTLibrary fileName is 'C:\Windows\SYSTEM32\ucrtbase.DLL' and in this library many functions is not available

**Comment by FunctionPoint** [comment]
Really? I'm getting a ton of warnings and errors when building.
Do you use any specific settings in VS2015?

**Comment by jgfoster** [comment]
@objectarts, I'd be interested in your comments on this. It seems that in general VM developers should be on the same toolset. That is, I'd prefer not to have to check all my edits in VS2013 as well as VS2015. As I've been able to contribute to getting the Debug configuration working in VS2013 I suspect that I could get things working in VS2015 but would be reluctant to do so unless you plan to have everyone move to this version. If your intent is to stay on VS2013 (which is fine by me), then perhaps this issue should be closed (to reduce my cognitive load in reviewing potential tasks!).

**Comment by blairmcg** [comment]
We may as well move to VS2015. I'm planning to take a look at it over the weekend.

**Comment by FunctionPoint** [comment]
Hi Blair, that would be very nice indeed!!

**Comment by blairmcg** [comment]
This is a bit trickier than I thought it would be - it was relatively easy to solve the build issues, and the resulting VM appears functional in that the image starts, but it fails quickly due to [significant changes in the C-runtime library](http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx). This is going to require some changes on the Smalltalk side of things (including in the boot image unfortunately), but seems worth doing since going forward the CRT will be shipped in the OS (it is already in Windows 10) and they will be maintaining backwards compatibility so it won't be necessary to worry about having the right VC Redist installed any more.

**Comment by FunctionPoint** [comment]
Ah, life is never _that_ easy. :). But thanks again for taking it up and hopefully the job is not too big.

**Comment by blairmcg** [comment]
As of commit fadbbe7 this is fixed.
